---

  - name: "Set OSX System language to English"
    command: "sudo languagesetup -langspec English"
    become: true

  - name: "Write NSDefaults using osxsettings.sh"
    shell: ./osxsettings.sh
