---
# Ansible playbook to secure your mac in one go!

  - name: "Block snooping in home-dirs"
    shell: chmod 700 /Users/*
    become: true

  - name: "Set permission on /Users/Shared"
    shell: chmod 1777 /Users/Shared
    become: true

  - name: "Set wake-on-lan"
    command: "systemsetup -setwakeonnetworkaccess on"
    become: true

  - name: "Enable Gatekeeper"
    shell: /usr/sbin/spctl --master-enable
    become: true

  - name: "Allow signed apps with Gatekeeper."
    shell:  /usr/sbin/spctl --enable --label 'Developer ID'
    become: true
